Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,7 +14,7 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: '16'
+          node-version: '22'
 
       - name: Install dependencies
         run: yarn
@@ -26,9 +26,12 @@ jobs:
         run: |
           sed -i "s/c8c30db3dddc4ad31065d336368c7905/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/g" wrangler.toml
 
+      - name: Initialize Production Environment
+        run: |
+          yarn init-prod || echo "Bucket already exists or another init error occurred, continuing with deployment..."
+
       - name: Deploy to Cloudflare
         run: |
-          yarn init-prod
           yarn deploy
         env:
           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
